# Generated by Django 4.2.13 on 2024-05-22 12:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_photo_post_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Blog',
        ),
        migrations.RenameIndex(
            model_name='blog',
            new_name='blog_blog_publish_1d1149_idx',
            old_name='blog_post_publish_bb7600_idx',
        ),
    ]
