# Generated by Django 4.2.13 on 2024-05-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_post_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='pubstatus',
            field=models.CharField(choices=[('PR', 'Private'), ('SH', 'Shared')], default='PR', max_length=2),
        ),
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='PB', max_length=2),
        ),
    ]
