# Generated by Django 4.2.13 on 2024-05-25 11:01

import autoslug.fields
import cloudinary.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_photo_caption'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='photo',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='image', unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
