# Generated by Django 4.2.13 on 2024-05-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_photo_managers_photo_slug_alter_blog_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='photo',
            managers=[
            ],
        ),
    ]
